### PR TITLE
Add pagination params to devices list

### PR DESCRIPTION
**Pull request by rchodava**

### CODE REVIEW

**Review by seveibar — APPROVED** [review]
Note that the pagination object isnt exposed, so the sdk has to internally implement pagination a consumer cant/shouldnt implement, but i think providing these parameters should be allowed

**Comment by rchodava** [comment]
> Note that the pagination object isnt exposed, so the sdk has to internally implement pagination a consumer cant/shouldnt implement, but i think providing these parameters should be allowed

yeah, I liked the idea of a separate `listAll` which does the pagination within the client, with the `list` sort of just a thin wrapper on the HTTP API method - provides the parameters the API method accepts

Slight chance that if anyone is expecting `list` to already return all devices, this will be breaking. But I think no one is atm

**Comment by seveibar** [comment]
> yeah, I liked the idea of a separate listAll which does the pagination within the client, with the list sort of just a thin wrapper on the HTTP API method - provides the parameters the API method accepts

Hmm I'd prefer to just have pagination be automatically implemented. Why would we ever make someone implement pagination? That said these parameters aren't strictly related to pagination so I think it's totally fine to allow them- but I would always automatically paginate for the user unless the page size was excessive (in which case I would throw a special error)

**Comment by rchodava** [comment]
> > yeah, I liked the idea of a separate listAll which does the pagination within the client, with the list sort of just a thin wrapper on the HTTP API method - provides the parameters the API method accepts
> 
> Hmm I'd prefer to just have pagination be automatically implemented. Why would we ever make someone implement pagination? That said these parameters aren't strictly related to pagination so I think it's totally fine to allow them- but I would always automatically paginate for the user unless the page size was excessive (in which case I think we should throw a special error)

Do you mean a helper paginator object that's returned as a result from list-like methods? Yeah, that makes sense. And yeah, these parameters are not going to get in the way of that.

**Comment by seveibar** [comment]
> Do you mean a helper paginator object that's returned as a result from list-like methods? Yeah, that makes sense. And yeah, these parameters are not going to get in the way of that.

list-like methods should just always paginate for the full result set, otherwise `access_codes.list` couldn't return just a list of access codes- it would need to return a special object or we would have to introduce another method etc. the point of the SDK is to make interfacing the API really easy so I think pagination is a nice thing to not have to worry about unless you're doing http directly

**Pull request merged**
